### ISSUE TITLE
Possible bug in module correlation estimate when abs = FALSE

### ISSUE THREAD

**Issue by diogro** [timcdlucas/EMMLi#4]
Hey! I was looking over the code and noticed that in line 225 the possible correlations estimates for each group of correlations is always positive, even when ABS == FALSE. Shouldn't this argument allow for negative correlation estimates? Thanks!

**Comment by timcdlucas** [comment]
Sorry I thought I replied to this. Thanks for pointing out the bug and the PR. PR accepted and I'll upload to CRAN when I get a moment.

**Comment by diogro** [comment]
No problem! Thanks for the fast response.

**Comment by timcdlucas** [comment]
@diogro  Taken me forever, but just thought I'd let you know the bug fix is now on CRAN. Thanks again!

**Comment by diogro** [comment]
Great to hear, thanks @timcdlucas!
